export default {
  era_narrow_a: 'A',
  era_short_a: 'AD',
  era_long_a: 'Anno Domini',
  era_narrow_b: 'B',
  era_short_b: 'BC',
  era_long_b: 'Before Christ',
  month_narrow_1: 'J',
  month_short_1: 'Jan',
  month_long_1: 'January',
  month_narrow_2: 'F',
  month_short_2: 'Feb',
  month_long_2: 'February',
  month_narrow_3: 'M',
  month_short_3: 'Mar',
  month_long_3: 'March',
  month_narrow_4: 'A',
  month_short_4: 'Apr',
  month_long_4: 'April',
  month_narrow_5: 'M',
  month_short_5: 'May',
  month_long_5: 'May',
  month_narrow_6: 'J',
  month_short_6: 'Jun',
  month_long_6: 'June',
  month_narrow_7: 'J',
  month_short_7: 'Jul',
  month_long_7: 'July',
  month_narrow_8: 'A',
  month_short_8: 'Aug',
  month_long_8: 'August',
  month_narrow_9: 'S',
  month_short_9: 'Sep',
  month_long_9: 'September',
  month_narrow_10: 'O',
  month_short_10: 'Oct',
  month_long_10: 'October',
  month_narrow_11: 'N',
  month_short_11: 'Nov',
  month_long_11: 'November',
  month_narrow_12: 'D',
  month_short_12: 'Dec',
  month_long_12: 'December',
}
